for Maxim
labzunova/-TP-Semester-project pull request #6
Opened 2020-05-07 20:12 UTC by Sergei39

2020-05-07 20:23 UTC, maksimuimin requested changes

2020-05-07 20:23 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +        if ((myUser.profile.getLikes() == null) || (myUser.profile.getLikes().indexOf(lastUserInf.id) == -1)) {
Так нехорошо делать. Ты функцию 2 раза вызываешь, если первый раз она вернула не null, нет гарантии, что и во второй раз сделает так же. Нужна промежуточная переменная, в которую нужно сохранить лайки профиля

2020-05-07 20:23 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +    private MediatorLiveData<DataProfile> currentUser = new MediatorLiveData<>();
Медиатор лив дату не стоит хранить во ViewModel. За изменение этих данных отвечает другой класс, поэтому здесь не должно быть доступа на запись. Хранить стоит обычную LiveData

2020-05-07 20:23 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +    private MediatorLiveData<DataProfile> currentUser = new MediatorLiveData<>();
По теме для общего развития, погугли, что значит буква I в аббревиатуре SOLID, если интересно, почему я предлагаю сделать так

2020-05-07 20:23 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +                currentUser.postValue(new DataProfile(infUser, bitmap));
За хранение данных профиля должна отвечать не ViewModel

2020-05-08 13:43 UTC, maksimuimin requested changes
Вроде неплохо, комменты оставил

2020-05-08 13:43 UTC, maksimuimin commented on app/src/main/java/com/example/first/Profile.java
> +    public static class Matches {
Статический класс - не очень хорошее решение. Лучше заменить на массив в поле класса Profile

2020-05-08 13:43 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/ConstValue.java
> +}
Плохое решение, так как теряется смысл всех этих констант. Общее правило: имя переменный должно давать понимание о том, как она используется, а не что в ней лежит. Почему так, а не иначе? Пример:
- Тебе в проекте на несколько тысяч (десятков тысяч) строк встретился идентификатор ConstValue.DEFAULT. Что это значит? Кроме как выматериться и пойти читать код в классе ConstValue мне в голову ничего не приходит.
- Если тебе встречается идентификатор вида MyGestureManager.SIDE_DEFAULT (к примеру, я хз, откуда вы конкретно эту константу вынесли) всё становится понятно и лишний код читать не нужно.

2020-05-08 13:43 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/ConstValue.java
> +}
Сама принадлежность константы тому или иному классу тоже даёт много понимания, поэтому писать отдельный класс для констант очень плохо

2020-05-08 13:43 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/DogFragment.java
> +        v.setOnTouchListener(new OnSwipeListener(getContext(), v, mViewModel));
Какая-то странная штука. Зачем ViewModel передаётся в onSwipeListener?

2020-05-08 13:43 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/DogFragment.java
> +        animator.start();
Такую анимацию вроде можно на XML написать и переиспользовать. К слову, на анимации тоже есть свои гайдлайны на material.io и есть даже некоторые заготовленные анимации в стандартной библиотеке

2020-05-08 13:43 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +            userInf.postValue(null);
почему postValue, а не setValue?

2020-05-08 13:43 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +    private MediatorLiveData<UserInformation> userInf;
Это мем какой-то писать все поля рядышком, а одно через 4 функции от всех остальных? Я полчаса искал его

2020-05-08 13:43 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +            });
Стрёмный код, 90% тут бага есть. Что ты хотел сделать здесь?

2020-05-08 13:43 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/MainActivity.java
> +        InitView();
Хорошее решение. Дробим одну большую функцию на несколько, чтобы уменьшить сложность кода

2020-05-08 13:43 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +        swipe(ConstValue.DEFAULT);
Чта? Я хз, что это длает, но к свайпам ViewModel не должна иметь никакого отношения. Все жесты - это сущности по уровню абстракции соответствующе UI

2020-05-08 13:43 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +    public void swipe(int side) {
Ок, вроде осознал, что за свайп. Лучше сделать так:
- ViewModel хранит функции, которые дёргаются OnSwipeListener'ами из Activity
- Сам разбор, в какую сторону свайпнул пользователь и какую функцию из ViewModel нужно дёрнуть, выносим в Activity

2020-05-08 13:43 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +                    infUser = "Default";
Magic constant?

2020-05-09 14:53 UTC, Sergei39 commented on app/src/main/java/com/example/first/Profile.java
> +    public static class Matches {
Исправил, выделил в отдельный класс не статический

2020-05-09 14:54 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/ConstValue.java
> +}
Убрал константы из отдельного класса

2020-05-09 14:55 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/DogFragment.java
> +        v.setOnTouchListener(new OnSwipeListener(getContext(), v, mViewModel));
Реализовал немного другую логику, теперь не передается ViewModel

2020-05-09 14:58 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/DogFragment.java
> +        animator.start();
Переместил эту анимацию в XML

2020-05-09 14:59 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +            userInf.postValue(null);
Не особо понимал разницу между этими методами, сейчас вроде почитал, понял, исправил

2020-05-09 15:05 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +        swipe(ConstValue.DEFAULT);
Вроде исправил

2020-05-09 15:06 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +    public void swipe(int side) {
Вроде что то подобное сделал

2020-05-09 15:06 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +                    infUser = "Default";
Исправил

2020-05-09 15:18 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +            });
Здесь я жду когда придет информация в LiveData, сохраняю ее и отправляю в другую LiveData. Не особо понимаю что не так)

2020-05-09 20:33 UTC, DragonF0rm commented on app/src/main/java/com/example/first/Profile.java
> +    public static class Matches {
Имхо, это всё-таки должен быть вложенный, но не статический класс

2020-05-09 20:40 UTC, maksimuimin requested changes

2020-05-09 20:40 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/Storage/NetworkData.java
> +    public static final String NAME_BRANCH = "Profiles";
А почему этот идентификатор не в общем стиле? Не должно быть BRANCH_NAME?

2020-05-09 20:40 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
>      }
Я же говорил, ViewModel'и не должны ничего знать о свайпах

2020-05-09 20:40 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
>      }
Эти функции стоит назвать по выполняемому действию. Типа like/dislike

2020-05-09 20:40 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +    public LiveData<UserInformation> swipeRight() {
Репозиторий ничего не должен знать о свайпах. Он знает только об обработке данных

2020-05-09 20:41 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +                    infUser = "Default";
Approve

2020-05-09 20:42 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +    public void swipe(int side) {
Близко по логике, но плохо по неймингу функций. У тебя о свайпах знает только UI слой (Activity), все остальные знают только об обработке данных своего уровня абстракции. Я отписался подробнее ниже

2020-05-09 20:43 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +        swipe(ConstValue.DEFAULT);
Отписался ниже

2020-05-09 20:46 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +            });
Всё равно плохо понимаю. Попробуй давать нормальные имена переменным. newInf и newUserInf не понятно чем отличаются. Называй переменные по смыслу, а не по содержимому. В данном случае можно попробовать указать в названии того, кто апдейтит эту лив дату

2020-05-09 20:47 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +            userInf.postValue(null);
Approve

2020-05-09 20:48 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/DogFragment.java
> +        animator.start();
Не вижу в diff'е, ты точно на этот файл git add сделал?

2020-05-09 20:49 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/DogFragment.java
> +        animator.start();
Апдейт, это я тупой

2020-05-09 20:50 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/DogFragment.java
> +        animator.start();
Approve

2020-05-09 20:55 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/DogFragment.java
> +        v.setOnTouchListener(new OnSwipeListener(getContext(), v, mViewModel));
Увидел, но выходит как то криво: у тебя активити отвечает за фрагмент, и при этом фрагмент накидывает на активити какие-то листенеры, это неправильно. Фрагмент стоит воспринимать как заменяемый кусок активити. Он может общаться с родительской активити (хотя лучше не надо, если это не что-то вроде read only методов), но управлять ею он не должен

2020-05-09 20:55 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/ConstValue.java
> +}
Approve

2020-05-12 20:45 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +        if ((myUser.profile.getLikes() == null) || (myUser.profile.getLikes().indexOf(lastUserInf.id) == -1)) {
Если я правильно понял замечание, то вроде исправил

2020-05-12 20:46 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +                currentUser.postValue(new DataProfile(infUser, bitmap));
я так понял, что надо было только название поменять, вроде поменял

2020-05-12 20:48 UTC, Sergei39 commented on app/src/main/java/com/example/first/Profile.java
> +    public static class Matches {
У меня в файле InfRepo необходимо создать этот вложенный класс. И я как то не нашел элегантного способа, если не используя static. Только с костылями

2020-05-12 20:51 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/DogFragment.java
> +        v.setOnTouchListener(new OnSwipeListener(getContext(), v, mViewModel));
Немного изменил, теперь листенер общается только с фрагментом, а фрагмент вызывает методы в активити. Может это не очень правильно что фрагмент вызывает что то в активити, но там вроде как по мне боле менее красиво все получилось

2020-05-12 20:52 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +            });
Изменил названия переменных, мб будет полегче читаться

2020-05-12 20:53 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +    public void swipe(int side) {
Изменил названия методов во всех компонентах

2020-05-12 20:53 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/Storage/NetworkData.java
> +    public static final String NAME_BRANCH = "Profiles";
Изменил

2020-05-12 20:53 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
>      }
Поменял

2020-05-12 20:54 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +    public LiveData<UserInformation> swipeRight() {
Поменял

2020-05-12 20:54 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +        swipe(ConstValue.DEFAULT);
Изменил

2020-05-12 20:59 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +    private MediatorLiveData<DataProfile> currentUser = new MediatorLiveData<>();
Я вроде почитал про это все, но как то не до конца понял, как связанно разделение интерфейсов в данном случае. У меня вроде не происходит изменений данных, приходящих в LiveData репозитория. Я принимаю эти данные и по ним создаю новые понятные для UI и передаю их в новой LiveData

2020-05-15 06:35 UTC, DragonF0rm commented on app/src/main/java/com/example/first/Profile.java
> +    public static class Matches {
Ок, не будем на это время тратить, Done

2020-05-15 06:36 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/DogFragment.java
> +        v.setOnTouchListener(new OnSwipeListener(getContext(), v, mViewModel));
Это уже лучше, но было бы круто сделать так:

2020-05-15 06:49 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +    public static class TransportCase {
Зачем этот рефакторинг? Теперь название совершенно не отражает содержание класса

2020-05-15 06:49 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +        if ((myUser.profile.getLikes() == null) || (myUser.profile.getLikes().indexOf(lastUserInf.id) == -1)) {
Нет, не исправил. Ты всё равно вызываешь функцию дважды. Если из первого вызова она тебе вернула не null, нет никакой гарантии, что из второго вызова она тебе тоже вернёт не null.

2020-05-15 06:51 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +    private MediatorLiveData<DataProfile> currentUser = new MediatorLiveData<>();
Ага, изменения данных не происходит, так зачем оставлять возможность изменять данные? Тебе вполне подойдёт обычная LiveData

2020-05-15 06:57 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +    private MediatorLiveData<DataProfile> currentUser = new MediatorLiveData<>();
А, всё, сорян, это я не разобрался. Всё норм у тебя, Approve

2020-05-15 06:57 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +                currentUser.postValue(new DataProfile(infUser, bitmap));
Approve

2020-05-15 06:59 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +            });
Лучше не стало. Объясни словами, что в этом классе происходит?

2020-05-15 06:59 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +        swipe(ConstValue.DEFAULT);
Approve

2020-05-15 07:00 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
> +    public void swipe(int side) {
Approve

2020-05-15 07:00 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/Storage/NetworkData.java
> +    public static final String NAME_BRANCH = "Profiles";
Approve

2020-05-15 07:00 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/MainViewModel.java
>      }
Approve

2020-05-15 07:00 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +    public LiveData<UserInformation> swipeRight() {
Approve

2020-05-21 00:16 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +        if ((myUser.profile.getLikes() == null) || (myUser.profile.getLikes().indexOf(lastUserInf.id) == -1)) {
Вроде поправил

2020-05-21 00:17 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/DogFragment.java
> +        v.setOnTouchListener(new OnSwipeListener(getContext(), v, mViewModel));
Вроде сделал нечто похожее

2020-05-21 00:18 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +            });
Изменилась логика и соответственно код в этом компоненте и этот-го куска кода нет больше

2020-05-21 00:19 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +    public static class TransportCase {
Сначала подумал что так будет лучше. Сейчас изменил

2020-05-21 07:46 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +        if ((myUser.profile.getLikes() == null) || (myUser.profile.getLikes().indexOf(lastUserInf.id) == -1)) {
Approve

2020-05-21 07:47 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +    private MediatorLiveData<UserInformation> userInf;
Исправил, Approve

2020-05-21 07:47 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +            });
Approve

2020-05-21 07:48 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/InfRepo.java
> +    public static class TransportCase {
Approve

2020-05-21 09:14 UTC, maksimuimin requested changes
В целом, очень неплохо) Нужно немного порефакторить, я написал правки. Можно ещё поработать над логикой работы с базами данных внутри классов NetworkDatabase и LocalDatabase, но это лучше отдельной таской

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountActivity.java
>  //import com.facebook.imagepipeline.request.ImageRequest;
Выпиливаем закомментированный код

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/ApplicationModified.java
> +    }
Не очень аккуратный рефакторинг. Ты, переименовал InfRepo в InfoRepo, но в местах использования переменные не переименовал, это затрудняет поиск

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/ApplicationModified.java
> +    private LocalDatabase localDatabase;
Не уверен, что эти базы стоит выставлять наружу через Application. Ими управляет только CompositeDatabase, соответственно, знать о них должен только этот класс

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/database/CompositeDatabase.java
> +    public void getCaseProfile(final GetCaseProfileCallback caseCallback) {
В чём разница между MyCaseProfile и CaseProfile? И что это за сущность? Вы так саджест называете?

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/database/CredentialDatabase.java
> +public interface CredentialDatabase {
CredentialDatabase - не очень хорошее название. Словом credentials обычно называют логины-пароли, ключи доступа, другие данные, с помощью которых можно пройти авторизацию

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/database/local/ConverterData.java
> +public class ConverterData {
Тоже плохое название. ConverterData переводится как "данные о конвертере". В вашем случае правильнее назвать DataConverter "конвертер данных". Но и это не самое лучшее название, т.к. не отражает назначение класса (нет понимания того, какие данные конвертируются). Лучше назвать ImageConverter

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/database/local/Credential.java
> +public class Credential {
Это не Credential (см. коммент выше), скорее Profile

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/database/local/CredentialDb.java
> +@Database(entities = {Credential.class}, version = 2)
А откуда у вас вторая версия? Вы же ещё разрабатываете) Это нужно, чтобы на проде нормально можно было накатывать обновления. Во время разработки до продакшена принято переписывать первую версию

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/database/local/Credential.java
> +public class Credential {
Или User

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/database/local/LocalDatabase.java
> +    private List<Credential> allCred = null;
Лучше замените на Queue (Очередь), будет чуть удобнее работать

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/database/local/LocalDatabase.java
> +            }
Залогируйте хотя бы. А вообще, ошибки надо обрабатывать

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/database/local/LocalDatabase.java
> +            }
Аналогично

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/database/network/NetworkDatabase.java
> +                                    bmpImage = resizeBitmap(bmpImage);
Это разве не реализовано в ConverterData?

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/database/network/NetworkDatabase.java
> +    }
Не стоит это хранить в классе БД, лучше в отдельном классе

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/database/network/NetworkDatabase.java
> +        */
Убираем закомментированный код

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/database/network/NetworkDatabase.java
> +    interface AllIdCollBack {
CollBack не должно быть Callback ?

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/database/network/NetworkDatabase.java
> +    interface SeenCollBack {
Аналогично

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/executors/AppExecutors.java
> +public class AppExecutors {
Крутое решение, лайк

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/executors/AppExecutors.java
> +    }
Зачем тут 2 конструктора? Делаешь 1 конструктор без параметров и создаёшь спокойно свои экзекьюторы

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/repositories/InfoRepo.java
> +        //newCase = null;
Убираем закомментированный код

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/repositories/InfoRepo.java
> +            database.changeProfileByCase(changeUserCase);
Лишний else. Конструкции вида:
```
func () {
    if (predicate) {
        doWork()
    } else {
         doOtherWork()
    }
}
```
принято заменять на:
```
func () {
    if (predicate) {
         doWork()
         return
    }
    doOtherWork()
}
```
Это делается, чтобы уменьшить вложенность и упростить чтение кода

2020-05-21 09:14 UTC, maksimuimin commented on app/src/main/java/com/example/first/mainScreen/repositories/InfoRepo.java
> +            database.changeProfileByCase(changeUserCase);
Это называется паттерном Early Exit

2020-05-21 09:14 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/repositories/InfoRepo.java
> +            }
Обработать ошибки

2020-05-21 09:14 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/ui/MainActivity.java
> +                });
Огонь)

2020-05-21 09:14 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/ui/MainViewModel.java
> +    }
Как-то не очень понятно, что ты в этих функциях делаешь

2020-05-21 09:14 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/ui/MainViewModel.java
> +                    infoUser += userInformation.profile.getCity();
Уже проходили такое. Если в первый раз функция вернула не null, нет гарантии, что и во второй раз она вернёт не null. А ещё я плохо понимаю, почему здесь +=

2020-05-21 09:14 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/ui/OnSwipeListener.java
> +    private DogFragment.Listener mListener;
OnSwipeListener не должен зависеть ни от каких UI компонентов

2020-05-22 21:17 UTC, Sergei39 commented on app/src/main/java/com/example/first/AccountActivity.java
>  //import com.facebook.imagepipeline.request.ImageRequest;
Убрал

2020-05-22 21:17 UTC, Sergei39 commented on app/src/main/java/com/example/first/ApplicationModified.java
> +    }
Вроде во всех местах поменял

2020-05-22 21:17 UTC, Sergei39 commented on app/src/main/java/com/example/first/ApplicationModified.java
> +    private LocalDatabase localDatabase;
Да, согласен, переместил

2020-05-22 21:22 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/database/CompositeDatabase.java
> +    public void getCaseProfile(final GetCaseProfileCallback caseCallback) {
В первом храниться информация про профиль текущего пользователя, во втором про профиль который надо показать. Там хранится вся информация пользователя, и это вроде все одна сущность. И мб это не очень красиво разбивать на два метода, но по другому я как то не смог придумать

2020-05-22 21:23 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/repositories/InfoRepo.java
> +            }
Я написал TODO просто для обработки надо пользователю показывать что то, это либо фрагмент либо еще что то, я думал это уже в новой ветке делать

2020-05-22 21:25 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/ui/MainViewModel.java
> +    }
В одной и другой я вызываю метод на получение нового профиля. А в like еще и вызываю метод обработки данных, там дальше запишется либо like либо matches в базу данных

2020-05-22 21:27 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/ui/MainViewModel.java
> +                    infoUser += userInformation.profile.getCity();
Я вроде в самом начале получаю объект и он по идее уже не может как то измениться по ходу этой функции. А += я собираю сообщение из пришедших данных, чтобы отправить в ui

2020-05-22 21:27 UTC, Sergei39 commented on app/src/main/java/com/example/first/mainScreen/ui/OnSwipeListener.java
> +    private DogFragment.Listener mListener;
Поправил

2020-05-23 09:16 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/DogFragment.java
> +        v.setOnTouchListener(new OnSwipeListener(getContext(), v, mViewModel));
Approve

2020-05-23 09:17 UTC, DragonF0rm commented on app/src/main/java/com/example/first/AccountActivity.java
>  //import com.facebook.imagepipeline.request.ImageRequest;
Approve

2020-05-23 09:17 UTC, DragonF0rm commented on app/src/main/java/com/example/first/ApplicationModified.java
> +    }
Approve

2020-05-23 09:18 UTC, DragonF0rm commented on app/src/main/java/com/example/first/ApplicationModified.java
> +    private LocalDatabase localDatabase;
Approve

2020-05-23 09:18 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/database/CompositeDatabase.java
> +    public void getCaseProfile(final GetCaseProfileCallback caseCallback) {
Approve

2020-05-23 09:20 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/database/network/NetworkDatabase.java
> +        */
Approve

2020-05-23 09:21 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/repositories/InfoRepo.java
> +            }
TODO для такого норм

2020-05-23 09:21 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/repositories/InfoRepo.java
> +            }
Approve

2020-05-23 09:26 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/ui/MainViewModel.java
> +    }
Это не хорошо, потому что действия "дизлайк" и "получить новый профиль" - как-то не соответствуют друг другу. Правильно будет завести во ViewModel несколько методов:
- like
- dislike
- fetchNewProfile
И в обработчике дёргать несколько функций последовательно

2020-05-23 09:29 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/ui/MainViewModel.java
> +                    infoUser += userInformation.profile.getCity();
Ага, увидел, это типа серилизация. А почему такой странный формат? Как вы потом эту строку разгребаете?

2020-05-23 09:33 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/ui/OnSwipeListener.java
> +    private DogFragment.Listener mListener;
Approve

2020-05-23 09:39 UTC, maksimuimin requested changes

2020-05-23 09:39 UTC, DragonF0rm commented on app/src/main/java/com/example/first/mainScreen/ui/DogFragment.java
> +    }
Зачем тут этот интерфейс остался? Принимай просто OnTouchListener или OnSwipeListener и всё. Тебе незачем придумывать внутри фрагментов специфичные интерфейсы, просто пользуйся универсальными листенерами

2020-05-24 18:26 UTC, merged