Basic MVVM implementation review
labzunova/-TP-Semester-project pull request #7
Opened 2020-05-17 16:22 UTC by Penguin-Run

2020-05-21 12:37 UTC, maksimuimin requested changes

2020-05-21 12:37 UTC, maksimuimin commented on app/build.gradle
> +
Убираем закомментированный код

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountActivity.java
>  //import com.facebook.imagepipeline.request.ImageRequest;
Убираем закомментированный код (выше аналогично)

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountActivity.java
> +         */
Убираем закомментированнный код

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountActivity.java
> +        final long ONE_MEGABYTE = 1024*1024;
Делаем статической и убираем наверх

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountActivity.java
> +                photoProfil.setImageBitmap(resizeBitmap(bitmap, 600.0f));
Magic Constant

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountActivity.java
>      }
Лучше вынести в отдельный класс. Примерно такой же код есть в диффе Сергея, нужно написать для этого единую реализацию и дёргать из разных классов

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountEdit/AccountEditActivity.java
> +        if (requestCode == PICK_IMAGE_REQUEST && resultCode == RESULT_OK
А если resultCode != RESULT_OK?

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountEdit/EditActivityRepo.java
> +        // получаем кэш
Комментарий для сверхразумов?)

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountEdit/EditActivityRepo.java
> +        }
Лишний else. Конструкции вида:
```
func () {
    if (predicate) {
        doWork()
    } else {
         doOtherWork()
    }
}
```
принято заменять на:
```
func () {
    if (predicate) {
         doWork()
         return
    }
    doOtherWork()
}
```
Это делается, чтобы уменьшить вложенность и упростить чтение кода. Это называется паттерном EarlyExit

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountEdit/EditActivityRepo.java
> +                }
EarlyExit:
```
...
if (profile == null) {
    Log.d(...);
    return;
}
...
```

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountEdit/EditActivityRepo.java
> +                bitmap = resizeBitmap(bitmap, 600.0f);
Вынести в отдельный класс и использовать функцию (подробнее писал выше)

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountEdit/EditActivityRepo.java
> +        bitmap.compress(Bitmap.CompressFormat.JPEG, (int)(INITIAL_QUALITY*0.6), baos);
А можно в WEBP формат переводить? Он меньше места занимает

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountEdit/EditActivityRepo.java
> +                Log.d(TAG, "onFailure: in uploadAvatarImage()");
Было бы неплохо ещё логировать, что за ошибка, иначе невозможно будет дебажить. Например e.PrintTrace()

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountEdit/EditActivityRepo.java
> +    }
Аналогично, выносим отсюда в отдельный класс

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountEdit/EditActivityViewModel.java
> +    public void onDoneClicked(ProfileInfo profileInfo) {
Лучше переименовать. Во вьюмодели методы не должны зависеть от UI, соответственно, их имена должны отражать то, что будет сделано с данными, а не причину действия

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountEdit/EditActivityViewModel.java
> +        }
Если есть тривиальные геттер и сеттер, зачем поле объявлять приватным?

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountEdit/EditActivityViewModel.java
> +    public static class AvatarImage {
Почему статический класс?

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountEdit/EditActivityViewModel.java
> +    public static class ProfileInfo {
Аналогично комменту выше

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountEdit/EditActivityViewModel.java
> +        }
Аналогично комменту выше

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountEdit/GalleryFragment.java
> +    private static final String ITEM_ADD_IMAGE = "Open chooser";
Неиспользуемая константа? Возможно, ошибаюсь, но в этом диффе её никто не дёргает

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountEdit/GalleryFragment.java
> +                        // ПЕРЕДЕЛАТЬ ЧТОБЫ resizeBitmap ЗДЕСЬ НЕ ВЫЗЫВАЛСЯ
Для таких комментов пишем // TODO <...>, чтобы они не терялись (AndroidStudio и любая другая IDE умеет такие комменты находить)

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountEdit/GalleryFragment.java
> +                        // holder.image.setImageBitmap(AccountEditActivity.resizeBitmap(bitmap, 1000.0f));
Убираем закомментированный код

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountEdit/GalleryFragment.java
> +                        Toast.makeText(activity.getApplicationContext(), "No Such file or Path found!!", Toast.LENGTH_LONG).show();
Если это предполагается использовать на проде, а не в целях дебага, то строку в ресурсы убираем

2020-05-21 12:37 UTC, maksimuimin commented on app/src/main/java/com/example/first/AccountEdit/GalleryFragment.java
> +                        // implement image scaling
//TODO --//--

2020-05-21 12:37 UTC, DragonF0rm commented on app/src/main/java/com/example/first/AccountEdit/GalleryFragment.java
> +        if (requestCode == AccountEditActivity.PICK_IMAGE_REQUEST && resultCode == RESULT_OK
А если resultCode != RESULT_OK?

2020-05-21 12:37 UTC, DragonF0rm commented on app/src/main/java/com/example/first/AccountEdit/GalleryFragment.java
> +        if (filepath != null) {
Early exit

2020-05-21 12:37 UTC, DragonF0rm commented on app/src/main/java/com/example/first/AccountEdit/GalleryFragment.java
> +                    progressDialog.dismiss();
Точно dissmiss? Это вроде означает выход с отрицательным результатом

2020-05-21 12:37 UTC, DragonF0rm commented on app/src/main/java/com/example/first/AccountEdit/GalleryFragment.java
> +                            Toast.makeText(getContext(), "Failed " + e.getMessage(), Toast.LENGTH_SHORT).show();
Если это планируется использовать на продакшене, а не в целях дебага, то строку в ресурсы

2020-05-21 12:37 UTC, DragonF0rm commented on app/src/main/java/com/example/first/AccountEdit/GalleryFragment.java
> +        // getAdapter().notifyItemInserted(itemList.size()-1);
Чистим закомментированный код

2020-05-21 12:37 UTC, DragonF0rm commented on app/src/main/java/com/example/first/AccountEdit/GalleryFragment.java
> +                            progressDialog.setMessage("Uploaded " + (int)progress + "%");
Строку в ресурсы

2020-05-21 12:37 UTC, DragonF0rm commented on app/src/main/java/com/example/first/AccountEdit/GalleryFragment.java
> +    }
Какой сакральный смысл в этом коде?

2020-05-21 12:37 UTC, DragonF0rm commented on app/src/main/java/com/example/first/AccountEdit/ImagesPagerAdapter.java
> +    }*/
Чистим закомментированный код

2020-05-21 12:37 UTC, DragonF0rm commented on app/src/main/java/com/example/first/AccountEdit/PictureBrowser.java
> +        //imagePager.setOffscreenPageLimit(3);
Чистим

2020-05-21 12:37 UTC, DragonF0rm commented on app/src/main/res/layout/activity_account.xml
>              android:layout_marginRight="10dp"
Очень странные размеры. По гайдлайнам все размеры должны быть кратны 8dp (4dp для моленьких элементов)

2020-05-21 12:37 UTC, DragonF0rm commented on app/src/main/java/com/example/first/AccountEdit/ViewPagerItemFragment.java
> +                    // ПЕРЕДЕЛАТЬ ЧТОБЫ resizeBitmap ЗДЕСЬ НЕ ВЫЗЫВАЛСЯ
На такое пишем //TODO <текст комментария>

2020-05-21 12:37 UTC, DragonF0rm commented on app/src/main/java/com/example/first/AccountEdit/ViewPagerItemFragment.java
> +                    // image.setImageBitmap(AccountEditActivity.resizeBitmap(bitmap, 500.0f));
Чистим

2020-05-21 12:37 UTC, DragonF0rm commented on app/src/main/java/com/example/first/AccountEdit/ViewPagerItemFragment.java
> +            if (getArguments().getParcelable("imageRef") != null) {
Early exit

2020-05-21 12:37 UTC, DragonF0rm commented on app/src/main/java/com/example/first/AccountEdit/ViewPagerItemFragment.java
> +                imageRef = getArguments().getParcelable("imageRef");
Magic constant

2020-05-21 12:37 UTC, DragonF0rm commented on app/src/main/java/com/example/first/AccountEdit/ViewPagerItemFragment.java
> +        if (imageRef != null) {
Это нормальное поведение, если imageRef будет Null? Если нет, можно `@NotNull` аннотацию перед аргументом поставить

2020-05-21 12:37 UTC, DragonF0rm commented on app/src/main/java/com/example/first/AccountEdit/ProfileCash.java
> +    private String address;
Зачем Private, если есть сеттеры?

2020-05-24 13:26 UTC, Penguin-Run commented on app/src/main/java/com/example/first/AccountActivity.java
>      }
Нормально будет такой класс реализовать в виде обычного класса со статик методами и названием по типу ImageManager?

2020-05-24 13:33 UTC, Penguin-Run commented on app/src/main/java/com/example/first/AccountEdit/AccountEditActivity.java
> +        if (requestCode == PICK_IMAGE_REQUEST && resultCode == RESULT_OK
Думаю на такой случай достаточно Тост показать. Вроде никакой логики делать не надо если Image picker не сможет достать фотку.

2020-05-24 14:00 UTC, Penguin-Run commented on app/src/main/java/com/example/first/AccountEdit/EditActivityViewModel.java
> +    public static class AvatarImage {
Чтобы можно было эту обертку использовать в других архитектурный компонентах через EditActivityViewModel.AvatarImage

2020-05-24 14:05 UTC, Penguin-Run commented on app/src/main/java/com/example/first/AccountEdit/EditActivityRepo.java
> +        bitmap.compress(Bitmap.CompressFormat.JPEG, (int)(INITIAL_QUALITY*0.6), baos);
Да, метод такой формат поддерживает, попробовал - вроде корректно работает. Оставляю webp

Единственный минус - из консоли файрбейса теперь нормально предпросмотр не работает из-за этого формата.

2020-05-24 14:22 UTC, Penguin-Run commented on app/src/main/java/com/example/first/AccountEdit/EditActivityViewModel.java
> +        }
Разве что в ожидании какой то логики в будущем..

2020-05-24 19:28 UTC, merged